### ISSUE TITLE
Datasets for entail_templates.txt, contradict_templates.txt, gender_occupation_templates.txt

### ISSUE THREAD

**Issue by jacqueline-he** [sunipa/OSCaR-Orthogonal-Subspace-Correction-and-Rectification#1]
Hi!

Thank you for releasing the code to OSCaR. Maybe I missed something, but I don't think the following datasets entail_templates.txt, contradict_templates.txt, gender_occupation_templates.txt are included in oscar.zip in the data subfolder. I was wondering if they could be added, or if there is existing code to generate them.

Thanks! :)
Jacqueline

**Comment by t-li** [comment]
Hey, thanks for reporting. Have just added those files. Check it out.

**Comment by jacqueline-he** [comment]
Thank you! This was helpful.
